language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.1
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

script: "./gradlew clean check"

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
